// LuaCall (light version) by Sergey Rozhenko

#ifndef LuaCall_h
#define LuaCall_h

/*
Define _LuaCall_LuaCpp if Lua files are compiled as C++.
#define _LuaCall_LuaCpp
*/

/*
Define LUACALL_ONSTART and LUACALL_ONEND prior to including LuaCall.h to use
different 'start' and 'end' callback functions names in your file.
You can also redefine them in any place you want.
By default LuaCallStart and LuaCallEnd are used and assumed to be global
functions.
Define LUACALL_LUA to be the lua_State variable name used by LuaCall macros.
*/

/*
Define _LuaCall_NoVariadicMacros here or prior to including LuaCall.h if your
compiler doesn't support variadic macros.
#define _LuaCall_NoVariadicMacros
*/

/*----------------------------------------------------------
 Internal Defines
*/

#ifdef __cplusplus
	#define _LUACALL_INLINE static __inline
	#ifndef _LuaCall_LuaCpp
		#define _LuaCall_NeedExternC
	#endif
#else
	#define _LUACALL_INLINE static
#endif

#ifdef _LuaCall_NeedExternC
extern "C"
{
	#include "lua.h"
}
#else
#include "lua.h"
#endif

/* User Callbacks */

#ifndef LUACALL_ONSTART
#define LUACALL_ONSTART LuaCallStart
int LuaCallStart(lua_State *L, const char *name);
#endif

#ifndef LUACALL_ONEND
#define LUACALL_ONEND LuaCallEnd
int LuaCallEnd(lua_State *L, int code, int nargs);
#endif


/*----------------------------------------------------------
 Implementation
*/

/* Passing params */

_LUACALL_INLINE int _LuaCallParam(lua_State *L, int code, lua_Number param)
{
	if (!code)
		lua_pushnumber(L, param);
	return code;
}

_LUACALL_INLINE int _LuaCallParam(lua_State *L, int code, const char *param)
{
	if (!code)
		lua_pushstring(L, param);
	return code;
}

/*----------------------------------------------------------
 Macros
*/


/* Variadic macros
 http://groups.google.com/group/comp.std.c/browse_thread/thread/77ee8c8f92e4a3fb/346fc464319b1ee5
 http://www.velocityreviews.com/forums/t680078-recursive-variadic-macros.html
 http://stackoverflow.com/questions/5134523/msvc-doesnt-expand-va-args-correctly
*/

#ifndef _LuaCall_NoVariadicMacros

/* _LuaCall_PP_NARG returns (n-1) instead of n returned by 'standard' PP_NARG */

#define _LuaCall_EXPAND(x) x
#define _LuaCall_PP_NARG(...) \
         _LuaCall_EXPAND(_LuaCall_PP_NARG_(__VA_ARGS__,_LuaCall_PP_RSEQ_N()))
#define _LuaCall_PP_NARG_(...) \
         _LuaCall_EXPAND(_LuaCall_PP_ARG_N(__VA_ARGS__))
#define _LuaCall_PP_ARG_N( \
          _1, _2, _3, _4, _5, _6, _7, _8, _9,_10, \
         _11,_12,_13,_14,_15,_16,_17,_18,_19,_20, \
         _21,_22,_23,_24,_25,_26,_27,_28,_29,_30, \
         _31,_32,_33,_34,_35,_36,_37,_38,_39,_40, \
         _41,_42,_43,_44,_45,_46,_47,_48,_49,_50, \
         _51,_52,_53,_54,_55,_56,_57,_58,_59,_60, \
         _61,_62,_63,N,...) N
#define _LuaCall_PP_RSEQ_N() \
         /*63,*/62,61,60,               \
         59,58,57,56,55,54,53,52,51,50, \
         49,48,47,46,45,44,43,42,41,40, \
         39,38,37,36,35,34,33,32,31,30, \
         29,28,27,26,25,24,23,22,21,20, \
         19,18,17,16,15,14,13,12,11,10, \
         9,8,7,6,5,4,3,2,1,0

#define _LuaCall_Paste(a,b) a ## b
#define _LuaCall_XPASTE(a,b) _LuaCall_Paste(a,b)
#define _LuaCall_CALL_(M, ...) _LuaCall_EXPAND(M(__VA_ARGS__))

#define LuaCall(...) _LuaCall_CALL_(_LuaCall_XPASTE(LuaCall, _LuaCall_PP_NARG(__VA_ARGS__)), __VA_ARGS__)

#endif

/* LuaCall auto-generated macros */
#define LuaCall0(name) LUACALL_ONEND(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), 0)
#define LuaCall1(name, a1) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), 1)
#define LuaCall2(name, a1, a2) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), 2)
#define LuaCall3(name, a1, a2, a3) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), 3)
#define LuaCall4(name, a1, a2, a3, a4) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), 4)
#define LuaCall5(name, a1, a2, a3, a4, a5) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), 5)
#define LuaCall6(name, a1, a2, a3, a4, a5, a6) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), 6)
#define LuaCall7(name, a1, a2, a3, a4, a5, a6, a7) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), 7)
#define LuaCall8(name, a1, a2, a3, a4, a5, a6, a7, a8) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), 8)
#define LuaCall9(name, a1, a2, a3, a4, a5, a6, a7, a8, a9) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), 9)
#define LuaCall10(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), 10)
#define LuaCall11(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), 11)
#define LuaCall12(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), 12)
#define LuaCall13(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), 13)
#define LuaCall14(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), 14)
#define LuaCall15(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), 15)
#define LuaCall16(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), 16)
#define LuaCall17(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), 17)
#define LuaCall18(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), 18)
#define LuaCall19(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), 19)
#define LuaCall20(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), 20)
#define LuaCall21(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), 21)
#define LuaCall22(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), 22)
#define LuaCall23(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), 23)
#define LuaCall24(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), 24)
#define LuaCall25(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), 25)
#define LuaCall26(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), 26)
#define LuaCall27(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), 27)
#define LuaCall28(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), 28)
#define LuaCall29(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), 29)
#define LuaCall30(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), 30)
#define LuaCall31(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), 31)
#define LuaCall32(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), 32)
#define LuaCall33(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), 33)
#define LuaCall34(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), 34)
#define LuaCall35(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), 35)
#define LuaCall36(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), 36)
#define LuaCall37(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), 37)
#define LuaCall38(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), 38)
#define LuaCall39(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), 39)
#define LuaCall40(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), 40)
#define LuaCall41(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), 41)
#define LuaCall42(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), 42)
#define LuaCall43(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), 43)
#define LuaCall44(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), 44)
#define LuaCall45(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), 45)
#define LuaCall46(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), 46)
#define LuaCall47(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), 47)
#define LuaCall48(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), 48)
#define LuaCall49(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), 49)
#define LuaCall50(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), 50)
#define LuaCall51(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), a51), 51)
#define LuaCall52(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), a51), a52), 52)
#define LuaCall53(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), a51), a52), a53), 53)
#define LuaCall54(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), a51), a52), a53), a54), 54)
#define LuaCall55(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), a51), a52), a53), a54), a55), 55)
#define LuaCall56(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55, a56) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), a51), a52), a53), a54), a55), a56), 56)
#define LuaCall57(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55, a56, a57) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), a51), a52), a53), a54), a55), a56), a57), 57)
#define LuaCall58(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), a51), a52), a53), a54), a55), a56), a57), a58), 58)
#define LuaCall59(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), a51), a52), a53), a54), a55), a56), a57), a58), a59), 59)
#define LuaCall60(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a60) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), a51), a52), a53), a54), a55), a56), a57), a58), a59), a60), 60)
#define LuaCall61(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a60, a61) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), a51), a52), a53), a54), a55), a56), a57), a58), a59), a60), a61), 61)
#define LuaCall62(name, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a60, a61, a62) LUACALL_ONEND(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, _LuaCallParam(LUACALL_LUA, LUACALL_ONSTART(LUACALL_LUA, name), a1), a2), a3), a4), a5), a6), a7), a8), a9), a10), a11), a12), a13), a14), a15), a16), a17), a18), a19), a20), a21), a22), a23), a24), a25), a26), a27), a28), a29), a30), a31), a32), a33), a34), a35), a36), a37), a38), a39), a40), a41), a42), a43), a44), a45), a46), a47), a48), a49), a50), a51), a52), a53), a54), a55), a56), a57), a58), a59), a60), a61), a62), 62)

#endif
